### ISSUE TITLE
Add a telemetry/metrics reporting from the plugin to collect usage data

### ISSUE THREAD

**Issue by royshil** [obs-ai/obs-backgroundremoval#355]
We can allow users to opt-in to send us anonymous information about their usage of the plugin
We can use e.g. FireBase C++ https://firebase.google.com/docs/analytics/cpp/start although it looks like a huge addition to the build
There are other options that use REST APIs

**Comment by umireon** [comment]
I suggest just starting with SDK and using REST APIs if the size becomes a problem.

**Comment by umireon** [comment]
I tried to include Firebase SDK but it requires some external dependencies such as OpenSSL and it will make building much harder.
I think it would be great to use REST API directly.

**Comment by royshil** [comment]
I'm afraid even a rest API would need SSL
But again we could and should use Qt since it's already bundled in OBS
I wonder if you can make a quick attempt to use Qt networking API for a simple request... If it works then we can figure out the telemetry endpoint

**Comment by umireon** [comment]
I will check that after #357 is merged.

**Comment by umireon** [comment]
Now this plugin imports the Qt networking library.

**Comment by royshil** [comment]
I think we can use AWS X-ray for segment events

https://sdk.amazonaws.com/cpp/api/LATEST/aws-cpp-sdk-xray/html/class_aws_1_1_x_ray_1_1_x_ray_client.html

**Comment by royshil** [comment]
i'm making very good progress on this in a feature branch. i'll bring it up for PR soon, just tying up some loose ends
