### ISSUE TITLE
Upgrade to new ONNX Runtime 1.16

### ISSUE THREAD

**Issue by royshil** [obs-ai/obs-backgroundremoval#442]
ONN Runtime 1.16 was just released
We can upgrade for performance and stability improvements.
https://github.com/microsoft/onnxruntime/releases/tag/v1.16.0

**Comment by umireon** [comment]
I'm working on building the static libraries of onnxruntime 1.16.0 on Windows.
https://github.com/umireon/onnxruntime-static-win/pull/7
