### ISSUE TITLE
Can we have GitHub Organization and GitHub Team?

### ISSUE THREAD

**Issue by umireon** [obs-ai/obs-backgroundremoval#446]
@royshil 

I have maintained the static binaries that are needed for obs-backgroundremoval.
Building them needs so many computing resources such as CPU time, CPU cores, memory, and disk and I cannot accommodate all of their building within unpaid GitHub Actions anymore.
I want to put the dependent libraries into a paid GitHub Organization to use the paid GitHub features such as larger runners.
It will be also great if the related resources are kept under the same organization.

I want to hear from you what you think about this plan.
I know you are too busy to discuss this but I hope we can come to some conclusions to solve the current situation.

Best,

**Comment by royshil** [comment]
@umireon That's an excellent suggestion.
I've been thinking of it and it makes sense to bring all the plugins and their related projects under one roof.

I've not seen any payments related blockage on the GitHub actions though.

Once I open an organization can I transfer all my OBS repos to it?

**Comment by umireon** [comment]
Yes at least we need the organization/

**Comment by royshil** [comment]
a new organization has been created! https://github.com/obs-ai

**Comment by royshil** [comment]
@umireon shuold we move obs-bgremoval to obs-ai ?
i already moved my other projects and i intent on starting new ones there

**Comment by umireon** [comment]
Yes, of course!
The old URL will be redirected to the new URL so it is safe to move repositories to organization.

**Comment by royshil** [comment]
cool i will transfer now
can you transfer your deps build repo as well?

**Comment by umireon** [comment]
Sure I will.

**Comment by royshil** [comment]
it's very easy to transfer a repo from the Settings page on the bottom "Transfer Ownership"
you should have permissions to do it since you're an organization member

**Comment by umireon** [comment]
I have done the procedure.

**Comment by royshil** [comment]
i'm closing this as done
