### ISSUE TITLE
Issue with background removal

### ISSUE THREAD

**Issue by LocoLosCollection** [obs-ai/obs-backgroundremoval#448]
So i recently downloaded the background removal from this website.  When i open up filters is shows background removal in the effects filter. I had seen a video that is shows up in the audio/video filter and works great. I seen your tut and when I'm adjusting the the background filter it does not change i had closed and reopened OBS and still no change.

**Comment by umireon** [comment]
Please describe the detail of your issue with your screenshot. I could not understand what is your problem.
And can you post here the URL of the video which says the plugin will appear in audio/video filter?

**Comment by umireon** [comment]
@royshil Can we close this issue as lack of information?

**Comment by LocoLosCollection** [comment]
I had sent screen shots of the issue

**Comment by umireon** [comment]
We don't have the screenshot yet.

**Comment by umireon** [comment]
Anyway you have to use our template to describe your issue.
